In [8]:
import numpy as np

def min_max_composition(A, B):
    m, n = A.shape
    n2, p = B.shape

    if n != n2:
        raise ValueError(f"Matrices dimensions incompatible: A is {m}×{n}, B is {n2}×{p}")

    C = np.zeros((m, p))

    for i in range(m):
        for j in range(p):
            min_values = []
            for k in range(n):
                min_values.append(min(A[i][k], B[k][j]))
            C[i][j] = max(min_values)

    return C

def min_max_prod_composition(A, B):
    m, n = A.shape
    n2, p = B.shape

    if n != n2:
        raise ValueError(f"Matrices dimensions incompatible: A is {m}×{n}, B is {n2}×{p}")

    C = np.zeros((m, p))

    for i in range(m):
        for j in range(p):
            products = []
            for k in range(n):
                products.append(A[i][k] * B[k][j])
            C[i][j] = max(products)

    return C

A = np.array([
    [0.2, 0.7, 0.5],
    [0.8, 0.3, 0.6]
])

B = np.array([
    [0.9, 0.4],
    [0.5, 0.8],
    [0.6, 0.2]
])

print("Matrix A (2×3):")
print(A)
print("\nMatrix B (3×2):")
print(B)

C_minmax = min_max_composition(A, B)
C_prod = min_max_prod_composition(A, B)

print()

print("MIN-MAX COMPOSITION")
print(C_minmax)

print()

print("MIN-MAX PROD COMPOSITION:")
print(C_prod)



Matrix A (2×3):
[[0.2 0.7 0.5]
 [0.8 0.3 0.6]]

Matrix B (3×2):
[[0.9 0.4]
 [0.5 0.8]
 [0.6 0.2]]

MIN-MAX COMPOSITION
[[0.5 0.7]
 [0.8 0.4]]

MIN-MAX PROD COMPOSITION:
[[0.35 0.56]
 [0.72 0.32]]
